run-name: Run Tests
on: [push]
jobs:



  tests-job:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      #----------------------------------------------
      #---- Checkout and install poetry and python
      #----------------------------------------------

      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      #----------------------------------------------
      #---- install dependencies
      #----------------------------------------------

      - name: poetry install
        run: poetry install

      #----------------------------------------------
      #---- show installation details
      #----------------------------------------------

      - name: poetry --version
        run: poetry --version
      - name: python --version in venv
        run: poetry run python --version
      - name: ls -lah
        run: ls -lah
      - name: poetry show
        run: poetry show

      #----------------------------------------------
      #---- Tests
      #----------------------------------------------

      - name: Run tests
        run: poetry run python testing/run_tests.py
