name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:



  tests-job:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.2.1"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry --version
        run: poetry --version
      - name: python --version in venv
        run: poetry run python --version
      - name: poetry install
        run: poetry install
      - name: poetry show
        run: poetry show
      - name: Test
        run: poetry run python testing/run_tests.py
